import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import JSZip from 'npm:jszip@3.10.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const { email, documents, formData, marketingOptIn = false } = await req.json();

    if (!email || !documents) {
      return Response.json({ error: 'Email and documents are required' }, { status: 400 });
    }

    // Create ZIP file
    const zip = new JSZip();
    
    // Add documents to ZIP
    Object.entries(documents).forEach(([name, content]) => {
      let finalContent = content;
      
      // Add watermark to text documents
      if (!name.includes('.txt') && !name.includes('.xml') && !name.includes('.json')) {
        finalContent = content + '\n\n---\n\nGenerated by Vox Animus SaaS Launch Kit\nhttps://vox-animus.com';
      }
      
      const filename = name.toLowerCase().replace(/\s+/g, '-');
      zip.file(filename, finalContent);
    });

    // Generate ZIP as base64
    const zipData = await zip.generateAsync({ type: 'base64' });

    // Upload ZIP to storage
    const zipBlob = Uint8Array.from(atob(zipData), c => c.charCodeAt(0));
    const zipFile = new File([zipBlob], 'documents.zip', { type: 'application/zip' });
    
    const uploadResult = await base44.asServiceRole.integrations.Core.UploadFile({
      file: zipFile
    });

    const downloadUrl = uploadResult.file_url;

    // Send email
    const emailBody = `Hi there,

Your documents have been generated and are ready to review.

What's included:
- Privacy Policy
- Terms of Service
- About Page
- Support Documentation

Download your documents here:
${downloadUrl}

(Link expires in 7 days)

─────────────────

Next step: Most founders have these reviewed by a lawyer before publishing. Services like Rocket Lawyer or LegalZoom typically cost $200-400 for review.

Questions? Just reply to this email.

Best,
The Annexa Team

Marketing updates: ${marketingOptIn ? 'Opted in' : 'Not opted in'}

─────────────────────────────────────────────

Annexa by Vox Animus OÜ
Tallinn, Estonia

These are professional templates. Most founders have 
them reviewed by a lawyer before going live.`;

    await base44.asServiceRole.integrations.Core.SendEmail({
      to: email,
      subject: 'Your Annexa Documents Are Ready',
      body: emailBody,
      from_name: 'Annexa'
    });

    return Response.json({ success: true });

  } catch (error) {
    console.error('Email error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});
