import React from 'react';
import { useNavigate } from 'react-router-dom';

export default function AnnexaTerms() {
  const navigate = useNavigate();

  return (
    <div className="max-w-4xl mx-auto px-6 py-12">
      <button
        onClick={() => navigate('/')}
        className="text-zinc-400 hover:text-white mb-8 flex items-center text-sm"
      >
        ← Back to Annexa
      </button>

      <article className="prose prose-invert prose-zinc max-w-none">
        <h1 className="text-4xl font-bold mb-2">Annexa Terms of Use</h1>
        <p className="text-zinc-400 mb-8">Last Updated: February 6, 2026</p>

        <h2>The Important Part (Read This)</h2>

        <h3>We Are Not a Law Firm</h3>
        <p>
          <strong>Vox Animus OÜ is NOT a law firm. We do NOT provide legal advice. Annexa is a document generation tool, not legal counsel.</strong>
        </p>

        <h3>No Attorney-Client Relationship</h3>
        <p>
          <strong>Using this tool does NOT create an attorney-client relationship with Vox Animus OÜ or anyone associated with it.</strong>
        </p>

        <h3>Get Real Legal Review</h3>
        <p>
          The documents generated by this tool are templates based on common practices. They are NOT reviewed by a lawyer for your specific situation.
        </p>
        <p>
          <strong>You MUST have a lawyer review these documents before using them.</strong>
        </p>
        <p>
          Different jurisdictions have different laws. What works in California might not work in Germany. We can't know your specific legal requirements.
        </p>

        <h3>No Warranties</h3>
        <p>We provide this tool "AS IS" with no warranties. We don't guarantee:</p>
        <ul>
          <li>The documents are legally sufficient</li>
          <li>The documents comply with your local laws</li>
          <li>The documents will protect you from legal liability</li>
          <li>The documents are error-free</li>
        </ul>

        <h2>What You're Agreeing To</h2>
        <p>By using Annexa, you agree:</p>
        <ol>
          <li><strong>You understand this is not legal advice</strong></li>
          <li><strong>You will get lawyer review before using generated documents</strong></li>
          <li><strong>You won't sue us if something goes wrong</strong></li>
          <li><strong>You're responsible for your own legal compliance</strong></li>
          <li><strong>You're at least 18 years old</strong></li>
          <li><strong>You have authority to make legal decisions for your business</strong></li>
        </ol>

        <h2>Acceptable Use</h2>

        <h3>You MAY:</h3>
        <ul>
          <li>Generate documents for your own products</li>
          <li>Edit the generated documents</li>
          <li>Share with your lawyer for review</li>
          <li>Use for commercial purposes</li>
        </ul>

        <h3>You MAY NOT:</h3>
        <ul>
          <li>Resell the generated documents</li>
          <li>Claim the documents are legally reviewed</li>
          <li>Use for illegal purposes</li>
          <li>Abuse the rate limits (scraping, automation)</li>
          <li>Reverse engineer the tool</li>
        </ul>

        <h2>Limitation of Liability</h2>
        <p><strong>TO THE MAXIMUM EXTENT PERMITTED BY LAW:</strong></p>
        <p>Vox Animus OÜ is NOT liable for:</p>
        <ul>
          <li>Legal issues arising from using generated documents</li>
          <li>Inaccurate or incomplete documents</li>
          <li>Data breaches or security issues</li>
          <li>Lost profits or business interruption</li>
          <li>Any damages exceeding $100 USD</li>
        </ul>
        <p>This applies even if we were told these problems might happen.</p>

        <h2>Indemnification</h2>
        <p>
          You agree to defend and hold harmless Vox Animus OÜ if someone sues us because of your use of Annexa.
        </p>
        <p>This includes legal fees and court costs.</p>

        <h2>Jurisdiction-Specific Disclaimers</h2>

        <h3>European Union (GDPR)</h3>
        <ul>
          <li>We process your data as described in our Privacy Policy</li>
          <li>You have rights under GDPR (see Privacy Policy)</li>
          <li>Data controller: Vox Animus OÜ, Estonia</li>
        </ul>

        <h3>California (CCPA)</h3>
        <ul>
          <li>You have rights under CCPA (see Privacy Policy)</li>
          <li>We don't sell personal information</li>
        </ul>

        <h3>Other Jurisdictions</h3>
        <ul>
          <li>These terms are governed by Estonian law</li>
          <li>Disputes resolved in Estonian courts</li>
          <li>If your local laws conflict, your local laws may apply</li>
        </ul>

        <h2>Payment Terms (EDGE Tier)</h2>

        <h3>Price</h3>
        <ul>
          <li>EDGE tier: $29 USD one-time</li>
          <li>Prices may change (existing customers grandfathered)</li>
          <li>No refunds after document delivery</li>
        </ul>

        <h3>Refunds</h3>
        <ul>
          <li>Full refund if documents fail to generate</li>
          <li>No refund after successful download</li>
          <li>Contact annexa@vox-animus.com within 24 hours</li>
        </ul>

        <h3>Stripe Processing</h3>
        <ul>
          <li>Payment handled by Stripe</li>
          <li>Subject to Stripe's terms and privacy policy</li>
          <li>We don't store your credit card information</li>
        </ul>

        <h2>Changes to Terms</h2>
        <ul>
          <li>We can update these terms anytime</li>
          <li>"Last Updated" date will change</li>
          <li>Continued use means you accept new terms</li>
        </ul>

        <h2>Termination</h2>
        <p>We can terminate your access if you:</p>
        <ul>
          <li>Violate these terms</li>
          <li>Abuse the rate limits</li>
          <li>Use for illegal purposes</li>
        </ul>
        <p>You can stop using the tool anytime (just close the page).</p>

        <h2>Severability</h2>
        <p>If one part of these terms is unenforceable, the rest still applies.</p>

        <h2>Contact</h2>
        <p>
          Questions: <a href="mailto:annexa@vox-animus.com" className="text-[#C24516] hover:underline">annexa@vox-animus.com</a>
        </p>
        <p>
          Legal: <a href="mailto:legal@vox-animus.com" className="text-[#C24516] hover:underline">legal@vox-animus.com</a>
        </p>

        <hr className="border-zinc-800 my-8" />
        <p className="text-sm text-zinc-500 text-center font-semibold">
          By using Annexa, you acknowledge you've read and agree to these terms.
        </p>
        <hr className="border-zinc-800 my-8" />
        <p className="text-sm text-zinc-500">
          Annexa is operated by Vox Animus OÜ, registered in Estonia.
        </p>
      </article>
    </div>
  );
}
