import React, { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Download, Edit, CheckCircle, Mail } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import SocialBios from '@/components/SocialBios';
import TierDebugPanel from '@/components/TierDebugPanel';
import { getUserTier } from '@/lib/tierUtils';

export default function Preview() {
  const location = useLocation();
  const navigate = useNavigate();
  const rawDocuments = location.state?.documents || {};
  const socialBios = location.state?.socialBios || {};
  const technicalFiles = location.state?.technicalFiles || {};
  const formData = location.state?.formData || {};

  // Use persistent tier from localStorage (survives page refresh)
  // Falls back to navigation state, then 'free'
  const tier = getUserTier() || location.state?.tier || 'free';

  // Combine documents with technical files for display
  const documents = {
    ...rawDocuments,
    'robots.txt': technicalFiles.robotsTxt || '',
    'sitemap.xml': technicalFiles.sitemapXml || '',
    'llms.txt': technicalFiles.llmsTxt || '',
    'brand-schema.json': technicalFiles.brandSchema ? JSON.stringify(technicalFiles.brandSchema, null, 2) : ''
  };

  const [selectedDoc, setSelectedDoc] = useState('Privacy Policy');
  const [expanded, setExpanded] = useState({});
  const [generationTime] = useState(() => Math.floor(Math.random() * 30) + 90); // 90-120 seconds
  const [dataPoints] = useState(() => Object.keys(formData).filter(k => formData[k]).length);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailAddress, setEmailAddress] = useState(formData.contact_email || '');
  const [emailSending, setEmailSending] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [marketingOptIn, setMarketingOptIn] = useState(false);

  const docList = [
    'Privacy Policy',
    'Terms of Use',
    'Cookie Policy',
    'About Us',
    'robots.txt',
    'sitemap.xml',
    'llms.txt',
    'brand-schema.json'
  ];

  const toggleExpand = (doc) => {
    setExpanded(prev => ({ ...prev, [doc]: !prev[doc] }));
  };

  const getPreview = (content) => {
    if (!content) return '';
    const words = content.split(' ').slice(0, 50).join(' ');
    return words + (content.split(' ').length > 50 ? '...' : '');
  };

  const getWordCount = (content) => {
    if (!content) return 0;
    return content.split(/\s+/).length;
  };

  const getDocBadge = (docName) => {
    if (docName === 'Privacy Policy' || docName === 'Cookie Policy') {
      return <span className="text-green-500 text-xs ml-2">●</span>;
    }
    return null;
  };

  const downloadDocument = (docName, content, withWatermark = true) => {
    let finalContent = content;

    if (withWatermark && !docName.includes('.txt') && !docName.includes('.xml') && !docName.includes('.json')) {
      finalContent = content + '\n\n---\n\nGenerated by Vox Animus SaaS Launch Kit\nhttps://vox-animus.com';
    }

    const blob = new Blob([finalContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = docName.toLowerCase().replace(/\s+/g, '-');
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadAll = (withWatermark = true) => {
    Object.entries(documents).forEach(([name, content]) => {
      setTimeout(() => downloadDocument(name, content, withWatermark), 100);
    });
  };

  const handleEdit = () => {
    navigate('/form', { state: { formData } });
  };

  const handleEmailDocuments = async () => {
    if (!emailAddress) return;

    setEmailSending(true);
    try {
      await base44.functions.invoke('emailDocuments', {
        email: emailAddress,
        documents,
        formData,
        marketingOptIn
      });
      base44.analytics.track({
        eventName: 'launch_kit_delivery_email_submitted',
        properties: {
          tier,
          marketing_opt_in: marketingOptIn
        }
      });
      setEmailSent(true);
      setTimeout(() => {
        setShowEmailModal(false);
        setEmailSent(false);
      }, 3000);
    } catch (err) {
      alert('Failed to send email. Please try again.');
    } finally {
      setEmailSending(false);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      <button
        onClick={() => navigate('/')}
        className="text-zinc-400 hover:text-white mb-6 flex items-center text-sm"
      >
        ← Start over with different inputs
      </button>

      <div className="mb-8">
        <h2 className="text-4xl font-bold mb-4">Your documents are ready</h2>

        {/* Metadata */}
        <p className="text-sm text-zinc-400 mb-6">
          Generated: {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })} • {formData.country} • {dataPoints} inputs • GDPR, CCPA compliant
        </p>

        {/* Document List */}
        <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-6 mb-6">
          <h3 className="text-lg font-semibold mb-4 text-white">8 documents generated:</h3>
          <div className="space-y-2">
            {docList.map(doc => (
              <div key={doc} className="flex items-center text-zinc-300">
                <CheckCircle className="w-4 h-4 text-green-500 mr-3 flex-shrink-0" />
                <span className="text-sm">{doc}</span>
              </div>
            ))}
          </div>

          <div className="mt-6 pt-6 border-t border-zinc-800">
            <p className="text-sm text-zinc-400">
              <strong className="text-zinc-300">Based on:</strong> {formData.company_name} • {formData.contact_email}
            </p>
          </div>
        </div>
      </div>

      <div className="flex gap-4 mb-12">
        <Button
          onClick={() => downloadAll(tier === 'free')}
          className="bg-[#C24516] hover:bg-[#a33912] text-white"
        >
          <Download className="w-4 h-4 mr-2" />
          Download all
        </Button>
        <Button
          onClick={() => setShowEmailModal(true)}
          variant="outline"
          className="bg-zinc-900 border-[#C24516] text-[#C24516] hover:bg-[#C24516] hover:text-white"
        >
          <Mail className="w-4 h-4 mr-2" />
          Email to me
        </Button>
        <Button
          onClick={handleEdit}
          variant="outline"
          className="bg-zinc-900 border-[#C24516] text-[#C24516] hover:bg-[#C24516] hover:text-white"
        >
          <Edit className="w-4 h-4 mr-2" />
          Edit
        </Button>
      </div>

      <div className="grid lg:grid-cols-4 gap-6">
        {/* Sidebar */}
        <div className="lg:col-span-1">
          <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-4 sticky top-6">
            <h3 className="font-bold mb-4 text-white">Documents</h3>
            <div className="space-y-2">
              {docList.map(doc => (
                <button
                  key={doc}
                  onClick={() => setSelectedDoc(doc)}
                  className={`w-full text-left px-3 py-2 rounded transition-colors ${selectedDoc === doc
                    ? 'bg-[#C24516] text-white'
                    : 'text-zinc-300 hover:bg-zinc-800'
                    }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="font-medium">{doc}</span>
                    {getDocBadge(doc)}
                  </div>
                  {documents[doc] && (
                    <div className="text-xs mt-1 text-zinc-500">
                      {getWordCount(documents[doc])} words
                    </div>
                  )}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Main Content */}
        <div className="lg:col-span-3 space-y-6">
          {/* EDGE: Social Bios */}
          {tier === 'edge' && socialBios && (
            <SocialBios formData={formData} socialBios={socialBios} />
          )}

          {/* Selected document full view */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-8">
            <div className="flex justify-between items-start mb-6">
              <h3 className="text-2xl font-bold">{selectedDoc}</h3>
              <Button
                onClick={() => downloadDocument(selectedDoc, documents[selectedDoc], tier === 'free')}
                variant="outline"
                size="sm"
                className="bg-zinc-900 border-[#C24516] text-[#C24516] hover:bg-[#C24516] hover:text-white"
              >
                <Download className="w-4 h-4 mr-2" />
                Download
              </Button>
            </div>
            <pre className="whitespace-pre-wrap text-zinc-300 font-mono text-sm leading-relaxed">
              {documents[selectedDoc]}
            </pre>
          </div>

          {/* Download options */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-8">
            <h3 className="text-2xl font-bold mb-4">Download Options</h3>

            <div className="space-y-4">
              <div className="border border-zinc-700 rounded-lg p-6">
                <div className="flex justify-between items-start mb-2">
                  <div>
                    <h4 className="font-bold text-lg">Free Version</h4>
                    <p className="text-zinc-400 text-sm">Includes "Generated by Vox Animus" attribution</p>
                  </div>
                  <span className="text-2xl font-bold text-[#C24516]">Free</span>
                </div>
                <div className="space-y-2 mt-4">
                  <Button
                    onClick={() => downloadAll(true)}
                    className="w-full bg-zinc-800 hover:bg-zinc-700 text-white"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download All (with watermark)
                  </Button>
                  <Button
                    onClick={() => setShowEmailModal(true)}
                    variant="outline"
                    className="w-full bg-zinc-900 border-[#C24516] text-[#C24516] hover:bg-[#C24516] hover:text-white"
                  >
                    <Mail className="w-4 h-4 mr-2" />
                    Email me a download link
                  </Button>
                </div>
              </div>

              {tier === 'edge' && (
                <div className="border-2 border-green-500/50 rounded-lg p-6 bg-zinc-900">
                  <div className="flex justify-between items-start mb-2">
                    <div>
                      <h4 className="font-bold text-lg flex items-center gap-2">
                        <CheckCircle className="w-5 h-5 text-green-500" />
                        Export Included
                      </h4>
                      <p className="text-zinc-400 text-sm">Professional documents with no branding</p>
                    </div>
                    <span className="text-2xl font-bold text-green-500">Included</span>
                  </div>
                  <Button
                    onClick={() => downloadAll(false)}
                    className="w-full mt-4 bg-green-600 hover:bg-green-700 text-white"
                  >
                    <Download className="w-4 h-4 mr-2" />
                    Download ZIP Without Branding
                  </Button>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Email Modal */}
      <Dialog open={showEmailModal} onOpenChange={setShowEmailModal}>
        <DialogContent className="bg-zinc-900 border-zinc-800 text-white">
          <DialogHeader>
            <DialogTitle className="text-xl font-bold">Where should we send the ZIP?</DialogTitle>
          </DialogHeader>

          {!emailSent ? (
            <div className="space-y-4">
              <p className="text-zinc-400 text-sm">
                We will email a ZIP download link for your documents.
              </p>
              <div>
                <Input
                  type="email"
                  placeholder="your@email.com"
                  value={emailAddress}
                  onChange={(e) => setEmailAddress(e.target.value)}
                  className="bg-zinc-800 border-zinc-700 text-white"
                />
              </div>
              <label className="flex items-start gap-2 text-xs text-zinc-400">
                <Checkbox
                  checked={marketingOptIn}
                  onCheckedChange={(checked) => setMarketingOptIn(Boolean(checked))}
                />
                <span>Send me optional product updates by email.</span>
              </label>
              <Button
                onClick={handleEmailDocuments}
                disabled={emailSending || !emailAddress}
                className="w-full bg-[#C24516] hover:bg-[#a33912] text-white"
              >
                {emailSending ? (
                  <>Sending...</>
                ) : (
                  <>
                    <Mail className="w-4 h-4 mr-2" />
                    Send ZIP
                  </>
                )}
              </Button>
            </div>
          ) : (
            <div className="py-6 text-center">
              <CheckCircle className="w-12 h-12 text-green-500 mx-auto mb-3" />
              <p className="text-lg font-medium mb-2">Check your inbox!</p>
              <p className="text-zinc-400 text-sm">
                We sent the documents to <strong className="text-white">{emailAddress}</strong>
              </p>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Development-only tier debug panel */}
      <TierDebugPanel />
    </div>
  );
}
